name: geocompr
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - r-base
  - r-sf
  - r-bookdown
  - r-cartogram
  - r-classInt
  - r-dplyr
  - r-geosphere
  - r-ggplot2
  - r-htmlwidgets
  - r-kableExtra
  - r-igraph
  - r-leaflet
  - r-lwgeom
  - r-osmdata
  - r-osrm
  - r-purrr
  - r-raster
  - r-rasterVis
  - r-rcartocolor
  - r-readr
  - r-revgeo
  - r-rmapshaper
  - r-s2
  - r-spData
  - r-stars
  - r-stringr
  - r-tibble
  - r-tidyr
  - r-tmap
  - r-tmaptools
 
