name: dev-sf
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: geocompr/geocompr:suggests
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Build book
          run: |
            Rscript -e 'remotes::install_github("r-spatial/sf")'
            Rscript -e 'bookdown::render_book("index.Rmd")'
        
