name: dev-osgeo-r
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: geocompr/geocompr:dev-osgeo
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Build book
          run: |
            Rscript -e 'remotes::install_dev("vctrs")'
            Rscript -e 'remotes::install_dev("dplyr")'
            Rscript -e 'remotes::install_dev("tmap")'
            Rscript -e 'remotes::install_github("rspatial/raster")'
            Rscript -e 'remotes::install_github("r-spatial/s2")'
            Rscript -e 'remotes::install_github("r-spatial/stars")'
            Rscript -e 'remotes::install_github("r-spatial/sf")'
            Rscript -e 'bookdown::render_book("index.Rmd")'
          
