on:
  push:
    branches:
      main
name: Render
jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    container: geocompr/geocompr:suggests
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        - name: Build book
          run: |
            Rscript -e 'remotes::install_github("r-spatial/sf")'
            Rscript -e 'remotes::install_github("r-spatial/stars")'
            Rscript -e 'remotes::install_github("rspatial/terra")'
            Rscript -e 'bookdown::render_book("index.Rmd")'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          publish_branch: gh-pages
          commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'
