name: qgis-ext
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    container: geocompr/geocompr:qgis
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'    
        
